version = 1

exclude_patterns = [
  "pnpm-workspace.yaml",
  "pnpm-lock.yaml"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[transformers]]
name = "prettier"